# Generated by Django 5.1.5 on 2025-01-20 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=uuid.uuid4, max_length=11, unique=True, verbose_name='Phone Number'),
        ),
    ]
