# Generated by Django 5.1.5 on 2025-01-23 15:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=uuid.uuid4, max_length=11, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(max_length=255, unique=True, verbose_name='Токен аутентификации'),
        ),
    ]
